name: "Build ,Push and deploy Docker image"

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:

        # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

        # Step 2: Get short commit hash
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

        # Step 3: Login to my Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Step 4: Login to my Docker Hub
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          # use the current dockerfile in this repo
          context: .
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ducklead-website:${{ env.SHORT_SHA }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ducklead-website:latest

      # Step 5: SSH into VPS and deploy
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            echo "Pulling new Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ducklead-website:latest

            echo "Stopping old container if running..."
            docker stop ducklead-website || true
            docker rm ducklead-website || true

            echo "Starting new container..."
            docker run -d \
              --name ducklead-website \
              -p 3000:80 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/ducklead-website:latest

            echo "Deployment complete!"

